name: pymigrate
services:
  postgres:
      image: postgres:18-alpine
      ports: 
        - "5432:5432"
      volumes:
        - type: volume
          source: postgresdata
          target: /var/lib/postgresql
      env_file:
        - ./.env
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 3s
        timeout: 3s
        retries: 3
  api:
    build:
      context: ./migrate-app
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    env_file:
      - ./migrate-app/.env
    depends_on:
      postgres:
        condition: service_healthy
  web:
    build:
      context: ./ng-migrate
      dockerfile: Dockerfile
    environment:
      NODE_ENV: PRODUCTION
    ports: 
      - "8080:80"
    depends_on:
      - api
volumes:
  postgresdata: