from datetime import datetime
from typing import Optional

from app.db.metadata import rds_metadata
from sqlmodel import Field, SQLModel

class InventoryEntry(SQLModel, table=True):
    metadata = rds_metadata
    __tablename__ = 'app_detallesentradainventario'

    id_entrada_inventario: int = Field(primary_key=True)
    idFake: Optional[int] = Field(default=None)
    idOriginal: Optional[int] = Field(default=None)
    folioExcel: Optional[int] = Field(default=None)
    idEntrada: Optional[str] = Field(default=None)
    codigo: Optional[str] = Field(default=None)
    sku: Optional[str] = Field(default=None)
    proceso: Optional[str] = Field(default=None)
    pestana: Optional[str] = Field(default=None)
    tipoDotacion: Optional[int] = Field(default=None)
    idTablaTipo: Optional[int] = Field(default=None)
    cantidad: Optional[int] = Field(default=None)
    descripcion: Optional[str] = Field(default=None)
    genero: Optional[str] = Field(default=None)
    pesoDotacion: Optional[float] = Field(default=None)
    kilates: Optional[int] = Field(default=None)
    idTablaKilates: Optional[int] = Field(default=None)
    precioBase: Optional[float] = Field(default=None)
    precioAdicional: Optional[float] = Field(default=None)
    precio: Optional[float] = Field(default=None)
    precioPiedra: Optional[float] = Field(default=None)
    costoBase: Optional[float] = Field(default=None)
    costoAdicional: Optional[float] = Field(default=None)
    costo: Optional[float] = Field(default=None)
    estadoPrenda: Optional[str] = Field(default=None)
    marca: Optional[str] = Field(default=None)
    pollera: Optional[int] = Field(default=None)
    modelo: Optional[str] = Field(default=None)
    serie: Optional[str] = Field(default=None)
    color: Optional[str] = Field(default=None)
    sub_categoria: Optional[str] = Field(default=None)
    tamano: Optional[str] = Field(default=None)
    tipoPrenda: Optional[int] = Field(default=None)
    idTablaTipoPrenda: Optional[int] = Field(default=None)
    observaciones: Optional[str] = Field(default=None)
    depreciacion: Optional[float] = Field(default=None)
    meses: Optional[int] = Field(default=None)
    maximo: Optional[float] = Field(default=None)
    idEmpeno: Optional[str] = Field(default=None)
    tipoContrato: Optional[int] = Field(default=None)
    sucursalOrigen: Optional[int] = Field(default=None)
    sucursalDestino: Optional[int] = Field(default=None)
    tipoEntrada: Optional[int] = Field(default=None)
    tipoSalida: Optional[int] = Field(default=None)
    precioVitrina: Optional[float] = Field(default=None)
    impuesto: Optional[int] = Field(default=None)
    cantidadPiedras: Optional[float] = Field(default=None)
    pesoPiedras: Optional[float] = Field(default=None)
    cantidadDiamantes: Optional[int] = Field(default=None)
    puntos: Optional[float] = Field(default=None)
    prestamoDiamante: Optional[float] = Field(default=None)
    idOrigen: Optional[int] = Field(default=None)
    destino: Optional[int] = Field(default=None)
    clasificacion: Optional[str] = Field(default=None)
    idReporte: Optional[int] = Field(default=None)
    fechaModificacion: Optional[datetime] = Field(default=None)
    actualizar: Optional[int] = Field(default=None)
    created_at: Optional[datetime] = Field(default=None)
    updated_at: Optional[datetime] = Field(default=None)