from datetime import datetime
from typing import Optional
from sqlalchemy import DateTime, Float, Integer, String, SmallInteger
from sqlalchemy.orm import Mapped, mapped_column
from app.db.mysql import MySQL

class InventoryEntry(MySQL):
    __tablename__ = "app_detallesentradainventario"

    id_entrada_inventario: Mapped[int] = mapped_column(Integer, primary_key=True)
    idFake: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    idOriginal: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    folioExcel: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    idEntrada: Mapped[Optional[str]] = mapped_column(String(25), nullable=True)
    codigo: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    sku: Mapped[Optional[str]] = mapped_column(String(25), nullable=True)
    proceso: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    pestana: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    tipoDotacion: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    idTablaTipo: Mapped[Optional[int]] = mapped_column(Integer(), nullable=True)
    cantidad: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    descripcion: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    genero: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    pesoDotacion: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    kilates: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    idTablaKilates: Mapped[Optional[int]] = mapped_column(Integer(), nullable=True)
    precioBase: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    precioAdicional: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    precio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    precioPiedra: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    costoBase: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    costoAdicional: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    costo: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    estadoPrenda: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    marca: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    pollera: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    modelo: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    serie: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    color: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    sub_categoria: Mapped[Optional[str]] = mapped_column(String(25), nullable=True)
    tamano: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    tipoPrenda: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    idTablaTipoPrenda: Mapped[Optional[int]] = mapped_column(Integer(), nullable=True)
    observaciones: Mapped[Optional[str]] = mapped_column(String(250), nullable=True)
    depreciacion: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    meses: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    maximo: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    idEmpeno: Mapped[Optional[str]] = mapped_column(String(25), nullable=True)
    tipoContrato: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    sucursalOrigen: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    sucursalDestino: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    tipoEntrada: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    tipoSalida: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    precioVitrina: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    impuesto: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    cantidadPiedras: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    pesoPiedras: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    cantidadDiamantes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    puntos: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    prestamoDiamante: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    idOrigen: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    destino: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    clasificacion: Mapped[Optional[str]] = mapped_column(String(25), nullable=True)
    idReporte: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    fechaModificacion: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    actualizar: Mapped[Optional[int]] = mapped_column(SmallInteger, nullable=True)
    created_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    updated_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
