from app.model.inventory_entry import InventoryEntry as IE
from app.model.pawn_type import PawnType as PT
from app.model.branch import Branch as Br
from app.model.carat_rating import CaratRating as K
from sqlmodel import Session, and_, desc, select

# def get_inventory_list(
#     branch_id: str, page: int, limit: int, search: str | None, rds: Session
# ):
#     page_index = page - 1
#     offset = page_index * limit

#     query = (
#         select(IE)
#         .join(Br, IE.sucursalDestino == Br.id)
#         .outerjoin(PT, IE.tipoDotacion == PT.idTipoEmpeno)
#         .outerjoin(K, IE.kilates == K.Clave)
#         .where(and_(IE.cantidad >= 1, IE.sucursalDestino == branch_id))
#         .order_by(desc(IE.id_entrada_inventario))
#     )

#     result = rds.exec(query.limit(limit).offset(offset)).all()

def get_inventory_list(branch_id: str, page: int, limit: int, query: str | None) -> tuple[list[dict], bool]:
    print({"branch_id": branch_id, "page": page, "limit": limit, "query": query})
    table = [
        {
            "barcode": "ELSSBTXDKEC3",
            "name": "Pulsera Mujer 15kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 14.4,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "446.95",
            "cost": "293.23",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMLAM-25-77118",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "VILLA LUCRE",
            "category": "Plata/958/Dije",
        },
        {
            "barcode": "71HQFPAR",
            "name": "Collar Mujer 12kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 14.0,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "354.61",
            "cost": "417.28",
            "observations": "",
            "pawn_no": "EMLA-24-36892",
            "stone_wght": 0.3,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "LOS ANDES METRO",
            "category": "Plata/999/Dije",
        },
        {
            "barcode": "JIJ7QZHYK1HD",
            "name": "Anillo Mujer 17kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 19.7,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "285.19",
            "cost": "365.96",
            "observations": "",
            "pawn_no": "EMCSMM-25-00508",
            "stone_wght": 9.8,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "EL BOSQUE TUMBA MUERTO",
            "category": "Oro/12/Collar",
        },
        {
            "barcode": "2ARICTIFAMJ",
            "name": "Arete Mujer 20kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 9.4,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "314.94",
            "cost": "386.10",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMCSMM-22-97677",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "VILLA LUCRE",
            "category": "Oro/12/Reloj",
        },
        {
            "barcode": "REPOEQEHTUS",
            "name": "Anillo Mujer 8kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 3.1,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "200.62",
            "cost": "336.74",
            "observations": "",
            "pawn_no": "EMLA-21-15547",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "MONTE OSCURO",
            "category": "Oro/20/Reloj",
        },
        {
            "barcode": "JOGTSMX2JWX4",
            "name": "Reloj Hombre 19kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 14.9,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "249.57",
            "cost": "409.84",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMVL-19-64450",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "CC SAN MIGUELITO METRO",
            "category": "Oro/14/Anillo",
        },
        {
            "barcode": "WIAB3F6YKHO7",
            "name": "Arete Mujer 17kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 7.1,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "352.35",
            "cost": "336.14",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMEBTM-23-20951",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "EL BOSQUE TUMBA MUERTO",
            "category": "Plata/999/Reloj",
        },
        {
            "barcode": "4PQRTB67UK",
            "name": "Pulsera Hombre 14kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 6.3,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "394.33",
            "cost": "250.93",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMEBTM-24-67501",
            "stone_wght": 16.2,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "LOS ANDES",
            "category": "Oro/18/Reloj",
        },
        {
            "barcode": "9THR83JXM",
            "name": "Dije Hombre 6kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 2.9,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "221.10",
            "cost": "146.51",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMMO-22-57360",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "SAN MIGUELITO",
            "category": "Oro/18/Pulsera",
        },
        {
            "barcode": "YZ4MYDPS",
            "name": "Arete Hombre 12kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 12.9,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "153.93",
            "cost": "108.69",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMSM-21-49269",
            "stone_wght": 14.5,
            "brand": "",
            "model": "",
            "series": "",
            "branch": "MONTE OSCURO",
            "category": "Plata/999/Collar",
        },
        {
            "barcode": "HITP82HCAHO",
            "name": "Pulsera Hombre 7kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 16.9,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "382.89",
            "cost": "387.38",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMVL-23-21737",
            "stone_wght": 0,
            "brand": "",
            "model": "",
            "series": "",
            "branch": "VILLA LUCRE",
            "category": "Oro/14/Anillo",
        },
        {
            "barcode": "9W2DYDLHEZW",
            "name": "Reloj Hombre 11kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 6.0,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "194.16",
            "cost": "338.63",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMVL-22-05394",
            "stone_wght": 7.5,
            "brand": "",
            "model": "",
            "series": "",
            "branch": "VILLA LUCRE",
            "category": "Oro/18/Collar",
        },
        {
            "barcode": "SZQDPRAGK",
            "name": "Reloj Mujer 9kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 6.6,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "350.42",
            "cost": "385.12",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMEBTM-21-94598",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "EL BOSQUE TUMBA MUERTO",
            "category": "Plata/958/Collar",
        },
        {
            "barcode": "TX8RTSYHQR0",
            "name": "Collar Hombre 6kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 17.4,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "420.55",
            "cost": "326.89",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMLA-21-86959",
            "stone_wght": 0,
            "brand": "",
            "model": "",
            "series": "",
            "branch": "VILLA LUCRE",
            "category": "Plata/958/Pulsera",
        },
        {
            "barcode": "WUPWGLB7PBF",
            "name": "Reloj Hombre 10kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 3.7,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "352.33",
            "cost": "130.59",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMEBTM-25-03605",
            "stone_wght": 15.2,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "VILLA LUCRE",
            "category": "Oro/8/Reloj",
        },
        {
            "barcode": "YF6OUYYH9",
            "name": "Dije Hombre 10kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 19.7,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "156.35",
            "cost": "330.70",
            "observations": "",
            "pawn_no": "EMVL-23-80409",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "LOS ANDES METRO",
            "category": "Plata/958/Pulsera",
        },
        {
            "barcode": "5MAAEUZUS2",
            "name": "Collar Hombre 11kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 12.6,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "201.81",
            "cost": "282.65",
            "observations": "",
            "pawn_no": "EMLA-25-48303",
            "stone_wght": 0,
            "brand": "",
            "model": "",
            "series": "",
            "branch": "MONTE OSCURO",
            "category": "Oro/12/Anillo",
        },
        {
            "barcode": "HAUYFV7XM",
            "name": "Anillo Mujer 6kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 16.5,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "210.41",
            "cost": "394.43",
            "observations": "",
            "pawn_no": "EMLAM-19-75846",
            "stone_wght": 2.9,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "VILLA LUCRE",
            "category": "Oro/18/Anillo",
        },
        {
            "barcode": "LGRQA6ZA",
            "name": "Anillo Hombre 18kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 10.8,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "239.30",
            "cost": "392.48",
            "observations": "",
            "pawn_no": "EMSM-20-88759",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "CC SAN MIGUELITO METRO",
            "category": "Oro/18/Reloj",
        },
        {
            "barcode": "VKCYSYVKIP",
            "name": "Reloj Hombre 15kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 3.1,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "375.43",
            "cost": "426.97",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMLAM-19-48526",
            "stone_wght": 0,
            "brand": "",
            "model": "",
            "series": "",
            "branch": "MONTE OSCURO",
            "category": "Plata/958/Anillo",
        },
        {
            "barcode": "ALNRJ4YJ",
            "name": "Collar Mujer 13kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 9.5,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "294.46",
            "cost": "232.88",
            "observations": "",
            "pawn_no": "EMEBTM-25-61036",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "MONTE OSCURO",
            "category": "Oro/20/Arete",
        },
        {
            "barcode": "CQDF2RDO7PN",
            "name": "Anillo Hombre 19kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 0.1,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "346.44",
            "cost": "410.21",
            "observations": "",
            "pawn_no": "EMLA-21-91920",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "LOS ANDES",
            "category": "Plata/925/Pulsera",
        },
        {
            "barcode": "JU4MUOYYY3",
            "name": "Dije Hombre 8kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 6.8,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "405.39",
            "cost": "385.44",
            "observations": "",
            "pawn_no": "EMLA-22-24980",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "MONTE OSCURO",
            "category": "Plata/958/Collar",
        },
        {
            "barcode": "BNZVVMDOA",
            "name": "Collar Mujer 15kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 0.4,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "208.31",
            "cost": "265.91",
            "observations": "",
            "pawn_no": "EMSM-24-35218",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "VILLA LUCRE",
            "category": "Plata/958/Arete",
        },
        {
            "barcode": "UOBUUH0WM6",
            "name": "Dije Hombre 18kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 4.0,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "113.62",
            "cost": "209.69",
            "observations": "",
            "pawn_no": "EMMO-22-23127",
            "stone_wght": 0,
            "brand": "",
            "model": "",
            "series": "",
            "branch": "SAN MIGUELITO",
            "category": "Oro/18/Arete",
        },
        {
            "barcode": "KFGXVKZJEJI",
            "name": "Reloj Hombre 14kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 9.1,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "356.91",
            "cost": "441.35",
            "observations": "",
            "pawn_no": "EMCSMM-19-04814",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "LOS ANDES",
            "category": "Plata/999/Arete",
        },
        {
            "barcode": "TSQ1IXGCW1",
            "name": "Collar Hombre 10kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 0.4,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "268.43",
            "cost": "176.17",
            "observations": "",
            "pawn_no": "EMMO-23-09097",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "LOS ANDES METRO",
            "category": "Oro/18/Collar",
        },
        {
            "barcode": "TU17B2REK",
            "name": "Dije Mujer 9kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 18.0,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "331.02",
            "cost": "102.50",
            "observations": "",
            "pawn_no": "EMMO-20-34096",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "LOS ANDES",
            "category": "Oro/10/Anillo",
        },
        {
            "barcode": "IAMSC2JHS7YY",
            "name": "Collar Hombre 4kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 3.7,
            "sellable": True,
            "buyable": False,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "442.90",
            "cost": "434.91",
            "observations": "",
            "pawn_no": "EMLA-23-95792",
            "stone_wght": 0,
            "brand": "OTRAS",
            "model": "",
            "series": "",
            "branch": "EL BOSQUE TUMBA MUERTO",
            "category": "Plata/925/Dije",
        },
        {
            "barcode": "4OGHCLWGE6O",
            "name": "Collar Mujer 10kg",
            "uom": "Unidades",
            "purchase_uom": "Unidades",
            "weight": 6.8,
            "sellable": False,
            "buyable": True,
            "product_type": "Producto Almacenable",
            "provider_tax": "ITBMS",
            "customer_tax": "ITBMS",
            "tags": "LOGICA DE ETIQUETAS",
            "rp": "416.37",
            "cost": "163.81",
            "observations": "lorem ipsum dolor sit amet",
            "pawn_no": "EMEBTM-19-31439",
            "stone_wght": 0,
            "brand": "",
            "model": "",
            "series": "",
            "branch": "EL BOSQUE TUMBA MUERTO",
            "category": "Plata/999/Collar",
        },
    ]

    start = max(0, page - 1) * limit
    end = start + limit

    return (table[start:end], end >= len(table))
