from dataclasses import dataclass
from datetime import datetime

@dataclass
class NormalizedItem:
    ie_inventory_entry_id: int
    ie_fake_id: int
    ie_original_id: int
    ie_excel_folio: int
    ie_entry_id: str
    ie_code: str
    ie_sku: str
    ie_process: str
    ie_tab: str
    ie_endowment_type: int
    ie_type_table_id: int
    ie_quantity: int
    ie_description: str
    ie_gender: str
    ie_endowment_weight: float
    ie_karats: int
    ie_karats_table_id: int
    ie_base_price: float
    ie_additional_price: float
    ie_price: float
    ie_stone_price: float
    ie_base_cost: float
    ie_additional_cost: float
    ie_cost: float
    ie_garment_condition: str
    ie_brand: str
    ie_pollera: int
    ie_model: str
    ie_serial: str
    ie_color: str
    ie_sub_category: str
    ie_size: str
    ie_garment_type: int
    ie_garment_type_table_id: int
    ie_notes: str
    ie_depreciation: float
    ie_months: int
    ie_maximum: float
    ie_pawn_id: str
    ie_contract_type: int
    ie_origin_branch: int
    ie_destination_branch: int
    ie_entry_type: int
    ie_exit_type: int
    ie_display_price: float
    ie_tax: int
    ie_stone_count: float
    ie_stone_weight: float
    ie_diamond_count: int
    ie_points: float
    ie_diamond_loan: float
    ie_origin_id: int
    ie_destination: int
    ie_classification: str
    ie_report_id: int
    ie_modified_at: datetime
    ie_update_flag: int
    ie_created_at: datetime
    ie_updated_at: datetime

    br_id: int
    br_table_id: int
    br_acronym: str
    br_key: int
    br_sort_order: int
    br_ip: str
    br_meraki: str
    br_legal_name: str
    br_trade_name: str
    br_alias: str
    br_rfc: str
    br_address: str
    br_city: str
    br_municipality: str
    br_district_id: int
    br_corregimiento_id: int
    br_phone: str
    br_zip_code: int
    br_region: str
    br_zone: str
    br_province: str
    br_latitude: str
    br_longitude: str
    br_pawn_schedule: str
    br_withdrawal_schedule: str
    br_wu_schedule: str
    br_sales_schedule: str
    br_fluyapp: str
    br_google_maps: str
    br_active: int
    br_account: str
    br_origin_id: int
    br_update_flag: int
    br_elconix_company: str
    br_elconix_cost_center: str
    br_fiscal_ruc: str
    br_fiscal_dv: str
    br_group: int
    br_visible: int
    br_migrated_at: datetime
    br_status: int
    br_deleted: int
    br_unit_manager_doc: str
    br_created_at: datetime
    br_updated_at: datetime

    pt_pawn_type_id: int
    pt_pawn_type_name: str
    pt_karats: int
    pt_type_weight: int
    pt_sort_order: int
    pt_expiration: int
    pt_origin_id: int
    pt_date: datetime
    pt_update_flag: int
    pt_status: int
    pt_created_at: datetime
    pt_updated_at: datetime

    cr_karat_id: int
    cr_key: int
    cr_karat_name: str
    cr_pawn_type_id: int
    cr_type_table_id: int
    cr_value_per_gram: float
    cr_sort_order: int
    cr_origin_id: int
    cr_modified_at: datetime
    cr_update_flag: int
    cr_status: int
    cr_created_at: datetime
    cr_updated_at: datetime
