from datetime import datetime
from typing import Optional
from sqlalchemy import DateTime, Integer, String
from sqlalchemy.orm import Mapped, mapped_column
from app.db.mysql import MySQL


class Branch(MySQL):
    __tablename__ = 'app_sucursales'
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    idTabla: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    siglas: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    clave: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    ordenamiento: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    ip: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    meraki: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    razonSocial: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    nombreComercial: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    alias: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    rfc: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    direccion: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    ciudad: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    municipio: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    idDistrito: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    idCorregimiento: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    telefono: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    cp: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    region: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    zona: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    provincia: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    latitud: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    longitud: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    horarioEmpenos: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    horarioRetiros: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    horarioWU: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    horarioVentas: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    fluyapp: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    googleMaps: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    activa: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    cuenta: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    IDOrigen: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    Actualizar: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    ElConix_Companie: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    ElConix_CentroCosto: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    rucFiscal: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    dvFiscal: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    grupo: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    visible: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    migrada: Mapped[Optional[datetime]] = mapped_column(DateTime, default=None)
    estado: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    eliminado: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    doc_jefe_unidad: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    created_at: Mapped[Optional[datetime]] = mapped_column(DateTime, default=None)
    updated_at: Mapped[Optional[datetime]] = mapped_column(DateTime, default=None)